# Generated by Django 4.2.20 on 2025-04-18 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LL', '0002_user_date_joined_user_is_active_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='shared_with',
            field=models.ManyToManyField(related_name='shared_notes', through='LL.SharedNote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sharednote',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sharednote',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_shared', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='sharednote',
            unique_together={('note', 'recipient')},
        ),
    ]
