# Generated by Django 4.2.20 on 2025-04-18 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LL', '0003_notes_shared_with_alter_sharednote_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='LL.subject'),
        ),
        migrations.AlterField(
            model_name='media',
            name='title',
            field=models.CharField(default='default_media_title', max_length=255),
        ),
        migrations.AlterField(
            model_name='notes',
            name='content',
            field=models.TextField(default='default_content'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.CharField(default='default_title', max_length=255),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(default='default_subject', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='default_password', max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='default_username', max_length=150, unique=True),
        ),
    ]
